---
abstract: 'Test-Moose-MockObjectCompile - a Helper module for testing compile time Moose stuff'
author: 'Jeremy Wall <jeremy@marzhillstudios.com>'
build_requires:
  Test::Exception: 0
  Test::Moose: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Test-Moose-MockObjectCompile
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Moose: 0
  Moose::Role: 0
  Symbol: 0
  perl: 5.6.0
version: 0.1
